spring:

  application:
    name: gateway-service

  cloud:
    gateway:
      httpserver:
        wiretap: false
      httpclient:
        wiretap: false
      discovery:
        locator:
          enabled: true
      metrics:
        enabled: true

logging:
  level:
    reactor.netty: DEBUG