spring:
  flyway:
    enabled: false
    baseline-on-migrate: false

  cloud:
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc.lob.non_contextual_creation: true
        default_batch_fetch_size: 50
        jdbc.batch_size: 30
        default_schema: app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5411/devices
    username: postgres
    password: postgres
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 20
      minimum-idle: 5       # Минимальное количество подключений в ожидании
      idle-timeout: 30000   # Тайм-аут ожидания (в миллисекундах) для неактивных соединений
      max-lifetime: 1800000 # Максимальное время жизни соединения (в миллисекундах)
      connection-timeout: 30000 # Тайм-аут для получения соединения из пула
      validation-timeout: 5000 # Тайм-аут для проверки соединения
      connection-test-query: SELECT 1

data-provider:
  resource: vek21

eureka:
  client:
    enabled: false

server:
  port: 8714