spring:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: advertisement-group
      enable-auto-commit: true
      auto-offset-reset: earliest
    properties:
      schema.registry.url: http://localhost:8085

  datasource:
    username: postgres_user_admin
    password: postgres_db_password
    url: jdbc:postgresql://localhost:5436/kufar-parser-db
  flyway:
    enabled: true
    baseline-on-migrate: true

  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8088