spring:

  kafka:
    bootstrap-servers: http://kafka:29092
    properties:
      schema.registry.url: http://schema-registry:8085

  datasource:
    url: jdbc:postgresql://kufar-parser-db:5432/kufar-parser-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true

  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver

eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  address: 0.0.0.0
  port: 8088