spring:
  application:
    name: user-application

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5434/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: app
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: none # либо update/create-drop, если ты это используешь
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: app
    baseline-on-migrate: true

server:
  port: 8012

