/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package by.zemich.parser.domain.model.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Parameter extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4448520340342941868L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Parameter\",\"namespace\":\"by.zemich.kufar.domain.model.events\",\"fields\":[{\"name\":\"identity\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"label\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Parameter> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Parameter> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Parameter> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Parameter> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Parameter> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Parameter to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Parameter from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Parameter instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Parameter fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String identity;
  private java.lang.String value;
  private java.lang.String label;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Parameter() {}

  /**
   * All-args constructor.
   * @param identity The new value for identity
   * @param value The new value for value
   * @param label The new value for label
   */
  public Parameter(java.lang.String identity, java.lang.String value, java.lang.String label) {
    this.identity = identity;
    this.value = value;
    this.label = label;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return identity;
    case 1: return value;
    case 2: return label;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: identity = value$ != null ? value$.toString() : null; break;
    case 1: value = value$ != null ? value$.toString() : null; break;
    case 2: label = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'identity' field.
   * @return The value of the 'identity' field.
   */
  public java.lang.String getIdentity() {
    return identity;
  }


  /**
   * Sets the value of the 'identity' field.
   * @param value the value to set.
   */
  public void setIdentity(java.lang.String value) {
    this.identity = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.String getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'label' field.
   * @return The value of the 'label' field.
   */
  public java.lang.String getLabel() {
    return label;
  }


  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.String value) {
    this.label = value;
  }

  /**
   * Creates a new Parameter RecordBuilder.
   * @return A new Parameter RecordBuilder
   */
  public static by.zemich.parser.domain.model.events.Parameter.Builder newBuilder() {
    return new by.zemich.parser.domain.model.events.Parameter.Builder();
  }

  /**
   * Creates a new Parameter RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Parameter RecordBuilder
   */
  public static by.zemich.parser.domain.model.events.Parameter.Builder newBuilder(by.zemich.parser.domain.model.events.Parameter.Builder other) {
    if (other == null) {
      return new by.zemich.parser.domain.model.events.Parameter.Builder();
    } else {
      return new by.zemich.parser.domain.model.events.Parameter.Builder(other);
    }
  }

  /**
   * Creates a new Parameter RecordBuilder by copying an existing Parameter instance.
   * @param other The existing instance to copy.
   * @return A new Parameter RecordBuilder
   */
  public static by.zemich.parser.domain.model.events.Parameter.Builder newBuilder(by.zemich.parser.domain.model.events.Parameter other) {
    if (other == null) {
      return new by.zemich.parser.domain.model.events.Parameter.Builder();
    } else {
      return new by.zemich.parser.domain.model.events.Parameter.Builder(other);
    }
  }

  /**
   * RecordBuilder for Parameter instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Parameter>
    implements org.apache.avro.data.RecordBuilder<Parameter> {

    private java.lang.String identity;
    private java.lang.String value;
    private java.lang.String label;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(by.zemich.parser.domain.model.events.Parameter.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.identity)) {
        this.identity = data().deepCopy(fields()[0].schema(), other.identity);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Parameter instance
     * @param other The existing instance to copy.
     */
    private Builder(by.zemich.parser.domain.model.events.Parameter other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.identity)) {
        this.identity = data().deepCopy(fields()[0].schema(), other.identity);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'identity' field.
      * @return The value.
      */
    public java.lang.String getIdentity() {
      return identity;
    }


    /**
      * Sets the value of the 'identity' field.
      * @param value The value of 'identity'.
      * @return This builder.
      */
    public by.zemich.parser.domain.model.events.Parameter.Builder setIdentity(java.lang.String value) {
      validate(fields()[0], value);
      this.identity = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'identity' field has been set.
      * @return True if the 'identity' field has been set, false otherwise.
      */
    public boolean hasIdentity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'identity' field.
      * @return This builder.
      */
    public by.zemich.parser.domain.model.events.Parameter.Builder clearIdentity() {
      identity = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public by.zemich.parser.domain.model.events.Parameter.Builder setValue(java.lang.String value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public by.zemich.parser.domain.model.events.Parameter.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'label' field.
      * @return The value.
      */
    public java.lang.String getLabel() {
      return label;
    }


    /**
      * Sets the value of the 'label' field.
      * @param value The value of 'label'.
      * @return This builder.
      */
    public by.zemich.parser.domain.model.events.Parameter.Builder setLabel(java.lang.String value) {
      validate(fields()[2], value);
      this.label = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'label' field.
      * @return This builder.
      */
    public by.zemich.parser.domain.model.events.Parameter.Builder clearLabel() {
      label = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Parameter build() {
      try {
        Parameter record = new Parameter();
        record.identity = fieldSetFlags()[0] ? this.identity : (java.lang.String) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.String) defaultValue(fields()[1]);
        record.label = fieldSetFlags()[2] ? this.label : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Parameter>
    WRITER$ = (org.apache.avro.io.DatumWriter<Parameter>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Parameter>
    READER$ = (org.apache.avro.io.DatumReader<Parameter>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.identity);

    out.writeString(this.value);

    out.writeString(this.label);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.identity = in.readString();

      this.value = in.readString();

      this.label = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.identity = in.readString();
          break;

        case 1:
          this.value = in.readString();
          break;

        case 2:
          this.label = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










