spring:

  kafka:
    bootstrap-servers: http://kafka:29092
    consumer:
      group-id: advertisement-group
      enable-auto-commit: true
      auto-offset-reset: earliest
    properties:
      schema.registry.url: http://schema-registry:8085

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5435/telegram-bot-db
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    hikari:
#      pool-name: HikariPool
#      maximum-pool-size: 20
#      minimum-idle: 5       # Минимальное количество подключений в ожидании
#      idle-timeout: 30000   # Тайм-аут ожидания (в миллисекундах) для неактивных соединений
#      max-lifetime: 1800000 # Максимальное время жизни соединения (в миллисекундах)
#      connection-timeout: 30000 # Тайм-аут для получения соединения из пула
#      validation-timeout: 5000 # Тайм-аут для проверки соединения
#      connection-test-query: SELECT 1

  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver

eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  address: 0.0.0.0
