spring:

  flyway:
    enabled: false

  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  address: 0.0.0.0
  port: 8081