spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://kufarspy-db:5432/kufardb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 20 
      minimum-idle: 5       # Минимальное количество подключений в ожидании
      idle-timeout: 30000   # Тайм-аут ожидания (в миллисекундах) для неактивных соединений
      max-lifetime: 1800000 # Максимальное время жизни соединения (в миллисекундах)
      connection-timeout: 30000 # Тайм-аут для получения соединения из пула
      validation-timeout: 5000 # Тайм-аут для проверки соединения
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc.lob.non_contextual_creation: true
        default_batch_fetch_size: 50 # Оптимизация пакетной выборки
        jdbc.batch_size: 30         # Оптимизация пакетных вставок
        default_schema: app

  flyway:
    enabled: true
    baseline-on-migrate: true


  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver



eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  address: 0.0.0.0
  port: 8081