spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  cloud:
    config:
      enabled: false

  flyway:
    enabled: false

server:
  port: 8085

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true