eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: false

server:
  port: 8888
  address: 0.0.0.0
