spring:
  profiles:
    active: dev
  application:
    name: configserver

  cloud:
    config:
      discovery:
        service-id: configserver
      server:
        git:
          uri: https://github.com/ZemichPS/kufarspy-config
          skipSslValidation: true
          force-pull: true
          ignore-local-ssh-settings: true

encrypt:
  key: ${ENCRYPT_KEY:secret}

