spring:
  application:
    name: email-service

  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085

  flyway:
    baseline-on-migrate: false
    community-db-support-enabled: false


  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

    config:
      enabled: false
      import: configserver:http://localhost:8888

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    enabled: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false # ????????
    fetch-registry: false
