spring:
  mail:
    host: smtp.rambler.ru
    username: partsflow@rambler.ru
    password: cs2402zzzXxx  # Проверьте пароль!
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 🔹 Обязательно для порта 465
          starttls:
            enable: false  # Отключаем, так как используем SSL
          connectiontimeout: 30000  # 30 секунд на подключение
          timeout: 30000  # 30 секунд на операции
          writetimeout: 30000  # 30 секунд на запись
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          socketFactoryFallback: false