spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  application:
    name: advertisement-service
  profiles:
    active: dev
#  cloud:
#    config:
#      enabled: false
#      discovery:
#        service-id: configserver
#        enabled: false



